project:
  type: website
  output-dir: "docs"

website:
  title: "Tesfaye Sebastiano Salarin"
  navbar:
    left:
    - text: "Home"
      file: index.qmd 
    - text: "CV"
      file: cv.qmd
    - text: "Presentations"
      file: talks.qmd
    - text: "Publications"
      file: Publications.qmd
    - text: "Contacts"
      file: Contacts.qmd
    #- text: "Public"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tesfayesalarin
      - icon: x
        href: https://x.com/TSalarin
      - icon: linkedin
        href: https://www.linkedin.com/in/tesfaye-salarin-8751b7184/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

